appff/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from dictionnaire import views

urlpatterns = [
    path('ff/admin/', admin.site.urls),
    path('ff/docff/', views.accueil_tables, name='accueil_docff'),
    path('ff/dump/', views.dump, name='dump'),
    re_path(r'^ff/doc_fftp/', include(('dictionnaire.urls', 'dicofftp'))),
    re_path(r'^ff/doc_ffta/', include(('dictionnaire_ta.urls','dicoffta'))),
]

dictionnaire_ta/urls.py
from django.urls import re_path

from . import views

app_name = 'dictionnaire_ta'

urlpatterns = [
    re_path(r'^$', views.accueil_doc, name='accueil_doc'),
    re_path(r'^table/(?P<table>[A-z0-9_]+)/(?P<variable_recherche>[A-z0-9_ ]{0,})$', views.doc_table, name='doc_table'),
    re_path(r'^recherche/$', views.recherche, name='recherche'),
]

dictionnaire_ta/models.py
'''

Copyright ou © ou Copr. Cerema, (juillet 2018) 

fichiers-fonciers@cerema.fr

Ce logiciel est un programme informatique servant à l'utilisation de la donnée FF

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.

'''

from django.db import models

class Variable(models.Model):
    """
    Class des variables des tables principales, récupère les valeurs associées aux champs de la table 
    """
    numero = models.IntegerField()
    nom = models.CharField(max_length = 255, null = True, blank=True)
    description = models.TextField(null = True, blank=True)
    observation = models.TextField(null = True, blank=True)
    formule_ini = models.CharField(max_length = 255, null = True, blank=True)
    origine = models.CharField(max_length = 255, null = True, blank=True)
    nature = models.CharField(max_length = 255, null = True, blank=True)
    lgr = models.CharField(max_length = 255, null = True, blank=True)
    table_associee = models.CharField(max_length = 255)
    
    
    def __str__(self):
        return self.nom + ' (' + self.table_associee + ')'
    
    @property
    def nature_variable(self):
        if self.nature=='X':
            nature='Caractère('+str(self.lgr)+')'
        elif self.nature=='Xt':
            nature='Tableau de caractères'
        elif str(self.nature)=='9' or str(self.nature)=='9.0':
            nature='Entier'
        elif self.nature=='9t':
            nature='Tableau de numériques'
        elif self.nature=='G':
            nature='Géométrie'
        else :
            nature='Non spécifié'
    
        return nature
    
class OrdreTables(models.Model):
    liste = models.CharField(max_length = 2550, null = True, blank=True)
    table = models.CharField(max_length = 2550, null = True, blank=True)

    @property
    #Impossible de stocker type list dans base de données donc str_to_lits recrée la liste
    def str_to_list(self):  
        cpt = 0
        mot = ""
        liste_mots = list()
        for i in list(self.liste):
            if i == "'":
                cpt+=1
            if cpt != 2 and i not in ["'", "[", "]", ",", " "]:
                mot += i
            if cpt == 2:
                cpt = 0
                liste_mots.append(mot.replace("'", ""))
                mot = ""
                
        return liste_mots

dictionnaire_ta/views.py
'''

Copyright ou © ou Copr. Cerema, (juillet 2018) 

fichiers-fonciers@cerema.fr

Ce logiciel est un programme informatique servant à l'utilisation de la donnée FF

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels lib res. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.

'''
import re
import csv
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.db.models.query import Q

from .description_tables import TABLES, lister_tables

from .models import Variable, OrdreTables


def accueil_doc(request):
    #Genere un tableau affichant la liste des tables principales
    context = {'tables' : TABLES}
    return render(request, 'accueil_ta.html', context)



def doc_table(request, table, variable_recherche):
    #Documentation d'une table
    nom_tables_permises = lister_tables()
    
    if table not in nom_tables_permises:
        raise Http404('Table inexistante')
       
    variables = Variable.objects.filter(table_associee = table).order_by('id')
    
    liste_ordre = ""
    ordre_table = OrdreTables.objects.filter(table = table)
    for ordre in ordre_table:
        liste_ordre = ordre.str_to_list
            
    return render(request, 'table_ta.html', locals())


def recherche(request):
    if request.method == 'POST':
        contexte_recherche = ContexteRechercheDoc(request.POST)                
        context = {'mots_clefs': contexte_recherche.mots_clefs,
                   'variables' : contexte_recherche.variables,}
        return render(request, 'recherche_doc_ta.html', context)
    else:
        raise Http404('Méthode POST incorrecte')

class ContexteRechercheDoc():

    def __init__(self, post):
        self.variables = []
        self.mots_clefs = '' 
        if 'motclef' in post:
            self.recherche(post['motclef'])
    
    def recherche(self, motclef):
        mots_clefs = self.decoupage(motclef)
        self.variables = self.resultat(mots_clefs)
        self.mots_clefs = ' '.join(mots_clefs)
    
    def decoupage(self, motclef):
        mots_clefs = re.findall(r'[\w]+',str(motclef))
        return [mot for mot in mots_clefs if (mot != '' and len(mot) >= 2)]
    
    def resultat(self, mots_clefs):
        y = Q()
        for mot in mots_clefs:
            y = y & (Q(nom__icontains=mot) | Q(description__icontains=mot))
        return Variable.objects.filter(y).distinct().order_by('nom')

dictionnaire_ta/templates/accueil_ta.html
{% extends "base_docff_ta.html" %}
{% load staticfiles %}

{% block contenu %}

<div class="page-header">
<div style="text-align: center">
			<img src="{% static "img/tables_agregees.png" %}" alt="Carte cliquable" usemap="#map">
			<MAP name=map>
			<AREA href="{% url 'dictionnaire_ta:doc_table' "section" "" %}" shape="rect" coords="45,620,200,640" alt="table_sections" title="table_sections">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "commune" "" %}" shape="rect" coords="45,565,195,585" alt="table_communes" title="table_communes">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "canton" "" %}" shape="rect" coords="45,495,195,510" alt="table_cantons" title="table_cantons">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "arrondissement" "" %}" shape="rect" coords="45,420,255,440" alt="table_arrondissements" title="table_arrondissements">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "departement" "" %}" shape="rect" coords="45,360,225,380" alt="table_departements" title="table_departements">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "region" "" %}" shape="rect" coords="45,295,185,320" alt="table_regions" title="table_regions">
			
			<AREA href="{% url 'dictionnaire_ta:doc_table' "carroyage" "" %}" shape="rect" coords="755,295,915,320" alt="carroy10km" title="carroy10km">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "carroyage" "" %}" shape="rect" coords="755,380,910,400" alt="carroy1km" title="carroy1km">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "carreaux_vides" "" %}" shape="rect" coords="755,400,885,420" alt="carroy1kmv" title="carroy1kmv">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "carroyage100" "" %}" shape="rect" coords="755,480,915,505" alt="carroy100m" title="carroy100m">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "carreaux_vides" "" %}" shape="rect" coords="755,505,880,520" alt="carroy100mv" title="carroy100mv">

			<AREA href="{% url 'dictionnaire_ta:doc_table' "pdlmp" "" %}" shape="rect" coords="520,295,665,315" alt="pdlmp" title="pdlmp">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "uf" "" %}" shape="rect" coords="520,405,725,425" alt="uf" title="uf">
			<AREA href="{% url 'dictionnaire_ta:doc_table' "TUP" "" %}" shape="rect" coords="520,500,700,530" alt="tup" title="tup">
			
			<AREA href="{% url 'dictionnaire_ta:doc_table' "batiment" "" %}" shape="rect" coords="285,295,455,315" alt="table_batiments" title="table_batiments">
			
			</MAP>
	</div>
<h3>Tables agrégées</h3>
</div>
{% for groupe_table in tables %}
<div class="panel panel-default">
    <div class="panel-heading">
	    <h3 class="panel-title"><i class="fa fa-table"></i> Tables essentielles</h3>
    </div>
    <div class="panel-body">

	<table class="table table-striped" width = "100 %">
		{% for table in groupe_table.desc_table %}
		<tr>
			{% for nom, description in table.items %}
			{% if nom == 'carroyage100' or nom == 'commune' or nom == 'TUP' %}
			<td width="20%" style="vertical-align: middle;"><a href="{% url 'dictionnaire_ta:doc_table' nom "" %}">{{nom}}</a></td>
			<td style="vertical-align: middle;">{{description}}</td>			
			{% endif %}
			{% endfor %}
		</tr>	
		{% endfor %}
	</table> 
	</div>
</div>

{% endfor %}

<div class="page-header">
{% for groupe_table in tables %}
<div class="panel panel-default">
    <div class="panel-heading">
	    <h3 class="panel-title"><i class="fa fa-table"></i> Autres tables</h3>
    </div>
    <div class="panel-body">

	<table class="table table-striped" width = "100 %">
		{% for table in groupe_table.desc_table %}
		<tr>
			{% for nom, description in table.items %}
			{% if nom != 'carroyage100' and nom != 'commune' and nom != 'TUP' %}
			<td width="20%" style="vertical-align: middle;"><a href="{% url 'dictionnaire_ta:doc_table' nom "" %}">{{nom}}</a></td>
			<td style="vertical-align: middle;">{{description}}</td>			
			{% endif %}
			{% endfor %}
		</tr>	
		{% endfor %}
	</table> 
	</div>
</div>
</div>

{% endfor %} 

{% endblock %} 

dictionnaire_ta/templates/base_docff_ta.html
{% extends "principal.html" %}
{% load staticfiles %}
 
{% block body %}
<div class="container">
    <div class="page-header espace-titre">
    	<div class="text-left">
    		<h3><a href = '{% url 'accueil_docff' %}' style="color:#333333"><i class="fa fa-home"></i> Accueil</a></h3>
    	</div>
          <div class="text-right">
        	<img src="{% static 'img/cerema_logo.png' %}"></img>
        </div>
    	<div class="text-left">
        	<h2><a href = '{% url "dictionnaire_ta:accueil_doc" %}' style="color:#333333"><i class="fa fa-book"></i> DocFF - dictionnaire des  Fichiers fonciers - Tables agrégées</a></h2>
        </div>
    </div>
    <form method="POST" action="{% url 'dictionnaire_ta:recherche' %}">
	<div class="row">
	   <div class="col-sm-offset-3 col-sm-6">  
		<div class="input-group">
		  <div class="input-group-btn">
		  	<a class="btn btn-default" href='{% url "dictionnaire_ta:accueil_doc" %}'><i class="fa fa-table"></i></a>
		    <button class="btn btn-default"><i class="fa fa-search"></i></button>
		  </div>
		  <input type="text" class="form-control" placeholder="Recherche" name="motclef">
		  {% csrf_token %}
		</div>
	   </div>
	</div>
	</form>
    
{% block contenu %}{% endblock %}

</div><!-- /.container -->

{% endblock %}

dictionnaire_ta/templates/recherche_doc_ta.html
{% extends "base_docff_ta.html" %}
{% load staticfiles %}

{% block contenu %}

<div class="page-header">
	<h3>Résultats<small> {{mots_clefs}}</small></a></h3>
</div>

{% if variables|length > 0 %}
<p><i class="fa fa-check"></i> indique la présence de la variable dans le dernier millésime.</p>
{% for variable in variables %}
	<div class="panel panel-default">
	    <div class="panel-heading">
		    <h3 class="panel-title">
		    	<i class="fa fa-star-o"></i> {{variable.nom}} (<a href='{% url "dictionnaire_ta:doc_table" variable.table_associee variable.nom %}'><i class="fa fa-table"></i> {{variable.table_associee}} (Accéder à la table)</a>)
		    </h3>
	    </div>
	    <div class="panel-body">
	    <p>Depuis millesime : {{variable.decrypt_syntax_millesime.0}}</p>
	    <p>Jusque millesime : {% if variable.decrypt_syntax_millesime.1 == None %} <i class="fa fa-check"></i> {% else %} {{variable.decrypt_syntax_millesime.1}} {% endif %}</p>
	   <p>Position dans la table : {{variable.numero}}</p>
	    <p>Description de la variable : {{variable.description}}</p>		
		</div>
	</div>
{% endfor %}

{% else %}

<h4>Aucun résultat trouvé pour {{mots_clefs}}.</h4>

{% endif %}

{% endblock %} 

dictionnaire_ta/templates/table_ta.html
{% extends "base_docff_ta.html" %}
{% load staticfiles %}
{% load template_filters %}

{% block contenu %}

<div class="page-header">
<h3><i class="fa fa-table"></i> Table {{table}}</h3>
</div>
<p><span style = 'background : #FFCB87'>Les champs surlignées sont des champs créés par le Cerema</span></p>
<br>
<table class="table-bordered table-striped table-condensed" width="100%">
	<tr>
		<th>N°</th>
		<th>Nom</th>
		<th>Description</th>
		<th>Observation</th>
		<th>Nature</th>
	</tr>
{% for var in liste_ordre %}
	{% for variable in variables %}
		{% if var == variable.nom %}
			{% if variable_recherche == variable.nom %}
    			<script>
    				$(function() {
    					 $('html, body').animate({scrollTop:$('#{{variable_recherche}}').offset().top}, 'slow');
    				});
    			</script>
			{% endif %}
		<tr {% if variable_recherche == variable.nom %} class="recherche" {% endif %}>
			<td {% if variable.origine == "Cerema" %} bgcolor = '#FFCB87' {% endif %}>{{liste_ordre|index:variable.nom}}<a id={{variable.nom}}></a></td>
			<td {% if variable.origine == "Cerema" %} bgcolor = '#FFCB87' {% endif %}>{{variable.nom}}</td>
			<td {% if variable.origine == "Cerema" %} bgcolor = '#FFCB87' {% endif %}>{{variable.description}}</td>
			<td {% if variable.origine == "Cerema" %}  bgcolor = '#FFCB87' {% endif %}>{% if variable.observation != NULL %} {{variable.observation}} {% endif %}</td>
			<td {% if variable.origine == "Cerema" %} bgcolor = '#FFCB87' {% endif %}>{{variable.nature_variable}}</td>
		</tr>
		{% endif %}
	{% endfor %}
{% endfor %}
</table>

{% endblock %} 