appff/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from dictionnaire import views

urlpatterns = [
    path('ff/admin/', admin.site.urls),
    path('ff/docff/', views.accueil_tables, name='accueil_docff'),
    path('ff/dump/', views.dump, name='dump'),
    re_path(r'^ff/doc_fftp/', include(('dictionnaire.urls', 'dicofftp'))),
    re_path(r'^ff/doc_ffta/', include(('dictionnaire_ta.urls','dicoffta'))),
]

dictionnaire/urls.py
from django.urls import re_path

from . import views

app_name = 'dictionnaire'

urlpatterns = [
    re_path(r'^$', views.accueil_doc, name='accueil_doc'),
    re_path(r'^table/(?P<table>[A-z0-9_]+)/(?P<url_millesime>[A-z0-9_]{0,5})/(?P<variable_recherche>[A-z0-9_ ]{0,})$', views.doc_table, name='doc_table'),
    re_path(r'^variable/(?P<table>[0-9a-z_]+)/(?P<variable>[0-9a-z_]+)$', views.desc_var, name='desc_var'),
    re_path(r'^recherche/$', views.recherche, name='recherche'),
]

dictionnaire_ta/urls.py
from django.urls import re_path

from . import views

app_name = 'dictionnaire_ta'

urlpatterns = [
    re_path(r'^$', views.accueil_doc, name='accueil_doc'),
    re_path(r'^table/(?P<table>[A-z0-9_]+)/(?P<variable_recherche>[A-z0-9_ ]{0,})$', views.doc_table, name='doc_table'),
    re_path(r'^recherche/$', views.recherche, name='recherche'),
]

dictionnaire/models.py
'''

Copyright ou © ou Copr. Cerema, (juillet 2018) 

fichiers-fonciers@cerema.fr

Ce logiciel est un programme informatique servant à l'utilisation de la donnée FF

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.

'''

from django.db import models
from builtins import property
    
class DescVariable(models.Model):
    """
    Class de la description de variables, récupère les valeurs associées aux champs de la table  dictionnaire_descvariable
    """
    #Récupère les valeurs des variables dans la table
    code = models.CharField(max_length = 255, null = True, blank=True)
    valeur = models.CharField(max_length = 255, null = True, blank=True)
    description = models.TextField(null = True, blank=True)
    observation = models.TextField(null = True, blank=True)
    millesime = models.CharField(max_length = 255, null = True, blank=True)
    var_associee = models.CharField(max_length = 255, null = True, blank=True)
    table_var_associee = models.CharField(max_length = 255, null = True, blank=True)
    
    def __str__(self):
        return self.code + ' - ' + self.var_associee + ' (' + self.table_var_associee + ')'
    
    @property
    def int_code(self):
        try :
            code_convert=int(float(self.code))
        except :
            code_convert=self.code
        return code_convert
        
    
    @property
    def decrypt_syntax_millesime(self):
        """
        Interprète la syntaxe jusque_millesime depuis_millesime de la table dictionnaire_descvariable
        """
        depuis_millesime = 2009
        jusque_millesime = None
        
        if self.millesime != None:
    
            # AAAA- (Depuis millésime)
            if len(self.millesime) == 5 and self.millesime[4] == "-":
                depuis_millesime = self.millesime[:4]
                jusque_millesime = None
            # AAAA-AAAA (Depuis millésime - jusque millésime)
            elif len(self.millesime) == 9 and self.millesime[4] == "-":
                depuis_millesime = self.millesime.split("-")[0]
                jusque_millesime = self.millesime.split("-")[1]
            # AAAA-AAAA|AAAA- (Depuis millésime et depuis millesime jusque millesime)
            elif "|" in self.millesime:
                depuis_millesime = self.millesime.split("|")[0]+" et depuis "+self.millesime.split("|")[1].split("-")[0]
                if self.millesime.split("|")[1].split("-")[1] == "":
                    jusque_millesime = None
                else:
                    jusque_millesime = self.millesime.split("|")[1].split("-")[1]
    
        return depuis_millesime, jusque_millesime

    
class Variable(models.Model):
    """
    Class des variables des tables principales, récupère les valeurs associées aux champs de la table 
    """
    #Récupère les valeurs des variables dans la table
    numero = models.IntegerField(null = True, blank=True)
    lgr = models.CharField(max_length = 255, null = True, blank=True)
    nat = models.CharField(max_length = 255, null = True, blank=True)
    nom = models.CharField(max_length = 255, null = True, blank=True)
    description = models.TextField(null = True, blank=True)
    observation = models.TextField(null = True, blank=True)
    origine = models.CharField(max_length = 255, null = True, blank=True)
    type = models.CharField(max_length = 255, null = True, blank=True)
    millesime = models.CharField(max_length = 255, null = True, blank=True)
    fiabilite = models.TextField(null = True, blank=True)
    doc = models.CharField(max_length = 255, null = True, blank=True)
    table_associee = models.CharField(max_length = 255, null = True, blank=True)
    modalites = models.ManyToManyField(DescVariable, blank = True)
    
    def __str__(self):
        return self.nom + ' (' + self.table_associee + ')'
    
    @property
    def url_doc(self):
        #Si doc existe, récupère la page associée au guide ou la fiche variable
        if self.doc != None:
            if self.doc.startswith("Doc"):
                return "guide.pdf#page="+self.doc.split()[1]
            elif self.doc.startswith("Fiche"):
                return "fiche_"+ self.doc.split()[1]+".pdf"
        return ''
        
    @property
    def decrypt_syntax_millesime(self):
        """
        Interpète la syntaxe de la colonne millesime pour l'afficher selon les variables depuis_millesime et jusque_millesime
        """
        depuis_millesime = 2009
        jusque_millesime = None
        
        if self.millesime != None:
    
            #AAAA- (Depuis millésime)
            if len(str(self.millesime)) == 5 and str(self.millesime[4]) == "-":
                depuis_millesime = self.millesime[:4]
                jusque_millesime = None
            #AAAA-AAAA (Depuis millésime - jusque millésime)
            elif len(str(self.millesime)) == 9 and str(self.millesime[4]) == "-":
                depuis_millesime = self.millesime.split("-")[0]
                jusque_millesime = self.millesime.split("-")[1]
            #AAAA-AAAA|AAAA- (Depuis millésime et depuis millesime jusque millesime)
            elif "|" in str(self.millesime):
                depuis_millesime = self.millesime.split("|")[0]+" et depuis "+self.millesime.split("|")[1].split("-")[0]
                if self.millesime.split("|")[1].split("-")[1] == "":
                    jusque_millesime = None
                else:
                    jusque_millesime = self.millesime.split("|")[1].split("-")[1]
    
        return depuis_millesime, jusque_millesime
    
    @property
    def modalite_variable(self):
        """
        Récupère toutes les modalites des variables
        """
        modalites_tables = self.modalites.all() 
        liste = []
        for variable_desc in enumerate(modalites_tables):
            liste.append(variable_desc[1])
        return liste
    
    @property
    def url_modalite(self):
        url_mod = None
        #Dans la liste des modalités, si une modalite existe alors variable_desc sera différent de []
        for variable_desc in enumerate(self.modalites.all()):
            if variable_desc[1] != []:
                url_mod = "/ff/doc_fftp/variable/"+self.table_associee+"/"+self.nom
        return url_mod
    
    @property
    def millesimes_dispo(self):
        # commentaire à rajouter
        liste_millesimes = [2009, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        liste_millesimes_var = list()
        
        depuis_millesime = 2009
        jusque_millesime = None
        
        if self.millesime != None:
    
            # 2009- et AAAA-
            if len(str(self.millesime)) == 5 and self.millesime[4] == "-":
                for k in liste_millesimes:
                    if k >= int(self.millesime[:4]):
                        liste_millesimes_var.append(int(k))
            #AAAA-AAAA
            elif len(str(self.millesime)) == 9 and self.millesime[4] == "-":
                liste_millesimes_var.append(int(self.millesime.split("-")[0]))
                for k in liste_millesimes[liste_millesimes.index(int(self.millesime.split("-")[0])):]:
                    if k <= int(self.millesime.split("-")[1]):
                        liste_millesimes_var.append(int(k))
            #AAAA-AAAA | AAAA- (ex : De 2009 à 2014 et depuis 2015)
            elif "|" in str(self.millesime):
                liste_millesimes_var.append(int(self.millesime.split("|")[0]))
                if self.millesime.split("|")[1].split("-")[1] == "":
                    for k in liste_millesimes:
                        if k >= int(self.millesime.split("|")[1].split("-")[0]):
                            liste_millesimes_var.append(int(k))
            #AAAA-AAAA | AAAA- (ex : De 2009 à 2014 et depuis 2015)
            elif "|" in str(self.millesime):
                liste_millesimes_var.append(int(self.millesime.split("|")[0]))
                if self.millesime.split("|")[1].split("-")[1] == "":
                    for k in liste_millesimes:
                        if k >= int(self.millesime.split("|")[1].split("-")[0]):
                            liste_millesimes_var.append(int(k))
                else:
                    for k in liste_millesimes:
                        if k >= int(self.millesime.split("|")[1].split("-")[1]):
                            liste_millesimes_var.append(int(k))
                        
        return liste_millesimes_var
            
class OrdreTables(models.Model):
    liste = models.CharField(max_length = 2550, null = True, blank=True)

dictionnaire/views.py
'''

Copyright ou © ou Copr. Cerema, (juillet 2018) 

fichiers-fonciers@cerema.fr

Ce logiciel est un programme informatique servant à l'utilisation de la donnée FF

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels lib res. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.

'''
import re
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.db.models.query import Q
from django.contrib.auth.decorators import login_required

from .description_tables import TABLES, lister_tables
from .models import Variable, OrdreTables
from appff.settings import BASE_DIR


@login_required
def dump(request):
    import os
    os.system(os.path.join(BASE_DIR, 'dumpdata.sh'))
    return HttpResponse('Dump terminé')

def accueil_tables(request):
    #Page d'accueil -> choix tables principales / tables agregees
    return render(request, 'accueil_tables.html')


def accueil_doc(request):
    #Genere un tableau affichant la liste des tables principales
    context = {'tables' : TABLES}
    return render(request, 'accueil.html', context)

def doc_table(request, table, url_millesime, variable_recherche):
    #correspond au niveau du tableau dune table
    #table et url_millesime proviennent de l'url
    #Si la table est innexistante, renvoie une erreur
    if table not in lister_tables():
        raise Http404('Table inexistante')
    
    #Si aucun millésime spécifique est demandé, affiche multi-millesime
        
    liste_ordre = ""
    ordre_table = OrdreTables.objects.filter(table = table)
    for ordre in ordre_table:
        liste_ordre = ordre.str_to_list
    
    #Récupère les objets de la classe Variable en fonction de la table (récupérée par l'url)  et les trie par id
    variables = Variable.objects.filter(table_associee = table).order_by('id')    
    liste_variables_millesime = list()

    liste_millesimes = [2009, 2011, 2012, 2013, 2014, 2015, 2016, 2017]#Ajouter année nouveau millesime pour modifer menu choix millesime

    for var in variables:
        #Dans le aucun où aucun millesime n'est demandé, affiche multi-millesime
        if url_millesime == "Multi":
            liste_variables_millesime.append(var)
        else:
            #Si le millesime demandé est présent dans la liste des millesimes de la variable, alors celle-ci est ajoutée
            try:
                if int(url_millesime) in var.millesimes_dispo:
                    liste_variables_millesime.append(var)
            except:
                raise Http404('Erreur de millésime')

    try:
        url_millesime = int(url_millesime)
    except:
        pass

    return render(request, 'table.html', locals())
    # locals renvoie toutes les variables de la fct doc_table

def desc_var(request, table, variable):
    #Si la table est innexistante, renvoie une erreur
    if table not in lister_tables():
        raise Http404('Table inexistante')
    #Récupère les objets de la classe Variable en fonction de la table (récupérée par l'url)  et les trie par id
    variables_desc_var = Variable.objects.filter(nom = variable).filter(table_associee = table).order_by('id')
    
    #Verifie si la variable existe
    if len(variables_desc_var) == 0:
        raise Http404('Variable inexistante')
    
    #Verifie si des modalites existent pour la variable concernée 
    #variables_desc_var est un QuerySet, le [0] permet de récuperer sa valeur
    variable = variables_desc_var[0]
    variable_desc = variable.modalite_variable
    #Conditions de vérification d'existence de modalités
    if variable_desc is None or len(variable_desc) == 0:
        raise Http404('Pas de modalités pour cette variable')
    
    return render(request, 'table_desc.html', locals())


def recherche(request):
    if request.method == 'POST':
        contexte_recherche = ContexteRechercheDoc(request.POST)                
        context = {'mots_clefs': contexte_recherche.mots_clefs,
                   'variables' : contexte_recherche.variables,}
        return render(request, 'recherche_doc.html', context)
    else:
        raise Http404('Méthode POST incorrecte')

class ContexteRechercheDoc():

    def __init__(self, post):
        self.variables = []
        self.mots_clefs = '' 
        if 'motclef' in post:
            self.recherche(post['motclef'])
    
    def recherche(self, motclef):
        mots_clefs = self.decoupage(motclef)
        self.variables = self.resultat(mots_clefs)
        self.mots_clefs = ' '.join(mots_clefs)
    
    def decoupage(self, motclef):
        mots_clefs = re.findall(r'[\w]+',str(motclef))
        return [mot for mot in mots_clefs if (mot != '' and len(mot) >= 2)]
    
    def resultat(self, mots_clefs):
        y = Q()
        for mot in mots_clefs:
            y = y & (Q(nom__icontains=mot) | Q(description__icontains=mot))
        return Variable.objects.filter(y).distinct().order_by('nom')




dictionnaire/templates/accueil.html
{% extends "base_docff.html" %}
{% load staticfiles %}

{% block contenu %}

<div class="page-header">
<div style="text-align: center">
			<img src="{% static "img/ff_modele_donnees.png" %}" alt="Carte cliquable" usemap="#map">

			<map name="map">
			<area href="{% url 'dictionnaire:doc_table' "pb40_pevprincipale" "Multi" "" %}" shape="rect" coords="30,65,150,120" alt="pb40" title="pb40">
			<area href="{% url 'dictionnaire:doc_table' "pb50_pevprofessionnelle" "Multi" "" %}" shape="rect" coords="30,135,150,190" alt="pb50" title="pb50">
			<area href="{% url 'dictionnaire:doc_table' "pb60_pevdependances" "Multi" "" %}" shape="rect" coords="30,205,150,260" alt="pb60" title="pb60">
			<area href="{% url 'dictionnaire:doc_table' "pb21_pev" "Multi" "" %}" shape="rect" coords="55,280,175,335" alt="pb21" title="pb21">
			<area href="{% url 'dictionnaire:doc_table' "pb30_pevexoneration" "Multi" "" %}" shape="rect" coords="30,350,150,405" alt="pb30" title="pb30">
			<area href="{% url 'dictionnaire:doc_table' "pb36_pevtaxation" "Multi" "" %}" shape="rect" coords="30,415,150,470" alt="pb36" title="pb36">
			<area href="{% url 'dictionnaire:doc_table' "pb0010_local" "Multi" "" %}" shape="rect" coords="285,280,405,335" alt="pb0010" title="pb0010">
			<area href="{% url 'dictionnaire:doc_table' "lots_locaux" "Multi" "" %}" shape="rect" coords="375,65,520,120" alt="lots_locaux" title="lots_locaux">
			<area href="{% url 'dictionnaire:doc_table' "pdl30_lots" "Multi" "" %}" shape="rect" coords="670,65,805,105" alt="pdl30" title="pdl30">
			<area href="{% url 'dictionnaire:doc_table' "pdl10_pdl" "Multi" "" %}" shape="rect" coords="670,130,805,200" alt="pdl10" title="pdl10">
			<area href="{% url 'dictionnaire:doc_table' "pdl20_parcellecomposante" "Multi" "" %}" shape="rect" coords="815,130,950,200" alt="pdl20" title="pdl20">
			<area href="{% url 'dictionnaire:doc_table' "pnb10_parcelle" "Multi" "" %}" shape="rect" coords="635,280,765,335" alt="pnb10" title="pnb10">
			<area href="{% url 'dictionnaire:doc_table' "pnb21_suf" "Multi" "" %}" shape="rect" coords="780,280,915,335" alt="pnb21" title="pnb21">
			<area href="{% url 'dictionnaire:doc_table' "pnb30_sufexoneration" "Multi" "" %}" shape="rect" coords="820,350,950,405" alt="pnb30" title="pnb30">
			<area href="{% url 'dictionnaire:doc_table' "pnb36_suftaxation" "Multi" "" %}" shape="rect" coords="820,415,950,470" alt="pnb36" title="pnb36">
			<area href="{% url 'dictionnaire:doc_table' "proprietaire_droit" "Multi" "" %}" shape="rect" coords="415,415,550,470" alt="proprietaire_droit" title="proprietaire_droit">
			<area href="{% url 'dictionnaire_ta:doc_table' "TUP" "" %}" shape="rect" coords="784,512,956,570" alt="tup" title="tup">

			</map>
	</div>
<h3>Tables principales</h3>
</div>
{% for groupe_table in tables %}
<div class="panel panel-default">
    <div class="panel-heading">
	    <h3 class="panel-title"><i class="fa fa-table"></i> Tables essentielles</h3>
    </div>
    <div class="panel-body">

	<table class="table table-striped" width = "100 %">
		{% for table in groupe_table.desc_table %}
		<tr>
			{% for nom, description in table.items %}
				{% if nom == 'pb0010_local' or nom == 'pnb10_parcelle' or nom == 'proprietaire_droit' or nom == 'TUP' %}
				{% if nom == 'TUP' %}
					<td width="20%" style="vertical-align: middle;"><a href="{% url 'dictionnaire_ta:doc_table' nom "" %}">{{nom}}</a></td>
					<td style="vertical-align: middle;">{{description}}</td>
				{% else %}
					<td width="20%" style="vertical-align: middle;"><a href="{% url 'dictionnaire:doc_table' nom "Multi" "" %}">{{nom}}</a></td>
					<td style="vertical-align: middle;">{{description}}</td>
				{% endif %}							
				{% endif %}
			{% endfor %}
		</tr>	
		{% endfor %}
	</table> 
	</div>
</div>

{% endfor %}

<div class="page-header">
{% for groupe_table in tables %}
<div class="panel panel-default">
    <div class="panel-heading">
	    <h3 class="panel-title"><i class="fa fa-table"></i> Autres tables</h3>
    </div>
    <div class="panel-body">

	<table class="table table-striped" width = "100 %">
		{% for table in groupe_table.desc_table %}
		<tr>
			{% for nom, description in table.items %}
				{% if nom != 'pb0010_local' and nom != 'pnb10_parcelle' and nom != 'proprietaire_droit' and nom != 'TUP' %}
					<td width="20%" style="vertical-align: middle;"><a href="{% url 'dictionnaire:doc_table' nom "Multi" "" %}">{{nom}}</a></td>
					<td style="vertical-align: middle;">{{description}}</td>			
				{% endif %}
			{% endfor %}
		</tr>	
		{% endfor %}
	</table> 
	</div>
</div>
</div>

{% endfor %} 

{% endblock %} 

dictionnaire/templates/base_docff.html
{% extends "principal.html" %}
{% load staticfiles %}
 
{% block body %}
<div class="container">
    <div class="page-header espace-titre">
    	 <div class="text-left">
    		<h3><a href = '{% url 'accueil_docff' %}' style="color:#333333"><i class="fa fa-home"></i> Accueil</a></h3>
    	</div>
          <div class="text-right">
        	<img src="{% static 'img/cerema_logo.png' %}"></img>
        </div>
    	<div class="text-left">
        	<h2><a href = '{% url 'dictionnaire:accueil_doc' %}' style="color:#333333"><i class="fa fa-book"></i> DocFF - dictionnaire des  Fichiers fonciers - Tables principales</a></h2>
        </div>
    </div>
    <form method="POST" action="{% url 'dictionnaire:recherche' %}">
	<div class="row">
	   <div class="col-sm-offset-3 col-sm-6">  
		<div class="input-group">
		  <div class="input-group-btn">
		  	<a class="btn btn-default" href='{% url 'dictionnaire:accueil_doc' %}'><i class="fa fa-table"></i></a>
		    <button class="btn btn-default"><i class="fa fa-search"></i></button>
		  </div>
		  <input type="text" class="form-control" placeholder="Recherche" name="motclef">
		  {% csrf_token %}
		</div>
	   </div>
	</div>
	</form>
    
{% block contenu %}{% endblock %}

</div><!-- /.container -->

{% endblock %}

dictionnaire/templates/recherche_doc.html
{% extends "base_docff.html" %}
{% load staticfiles %}

{% block contenu %}

<div class="page-header">
	<h3>Résultats<small> {{mots_clefs}}</small></a></h3>
</div>

{% if variables|length > 0 %}
<p><i class="fa fa-check"></i> indique la présence de la variable dans le dernier millésime.</p>
{% for variable in variables %}
	<div class="panel panel-default">
	    <div class="panel-heading">
		    <h3 class="panel-title">
		    {% if variable.url_modalite != None %}
		    	<i class="fa fa-star-o"></i><a href= '{{variable.url_modalite}}'>{{variable.nom}} (Accéder aux modalités)</a> (<a href="{% url 'dictionnaire:doc_table' variable.table_associee "Multi" variable.nom %}"><i class="fa fa-table"></i> {{variable.table_associee}} (Accéder à la table)</a>)
            {% else %}
                <i class="fa fa-star-o"></i> {{variable.nom}} (<a href="{% url 'dictionnaire:doc_table' variable.table_associee "Multi" variable.nom %}"><i class="fa fa-table"></i> {{variable.table_associee}} (Accéder à la table)</a>)
            {% endif %}
		    </h3>
	    </div>
	    <div class="panel-body">
	    <p>Depuis millesime : {{variable.decrypt_syntax_millesime.0}}</p>
	    <p>Jusque millesime : {% if variable.decrypt_syntax_millesime.1 == None %} <i class="fa fa-check"></i> {% else %} {{variable.decrypt_syntax_millesime.1}} {% endif %}</p>
	   <p>Position dans la table : {{variable.numero}}</p>
	    <p>Description de la variable : {{variable.description}}</p>		
		</div>
	</div>
{% endfor %}

{% else %}

<h4>Aucun résultat trouvé pour {{mots_clefs}}.</h4>

{% endif %}

{% endblock %} 

dictionnaire/templates/table_desc.html
{% extends "base_docff.html" %}
{% load staticfiles %}

{% block contenu %}

<div class="page-header">
<h4><a href = "{% url 'dictionnaire:doc_table' variable.table_associee "Multi" '' %}">Retour table {{table}}</a></h4>
<h3><i class="fa fa-table"></i> Doc variable {{variable.nom}} dans la table {{table}}</h3>
</div>
<p><i class="fa fa-check"></i> indique la présence de la variable dans le dernier millésime.</p>
<table class="table-bordered table-striped table-condensed" width="100%">
	<tr>
		<th>Code</th>
		<th>Valeur</th>
		<th>Description</th>
		<th>Observation</th>
		<th>Depuis millesime</th>
		<th>Jusque millesime</th>
	</tr>
	{% for variable in variable_desc %}
	<tr>
		<td>{{variable.int_code}}</td>
		<td>{{variable.valeur}}</td>
		<td>{{variable.description}}</td>
		<td>{{variable.observation}}</td>
		<td>{{variable.decrypt_syntax_millesime.0}}</td>
		<td><div>{% if variable.decrypt_syntax_millesime.1 == None %}<i class="fa fa-check"></i> {% else %} {{variable.decrypt_syntax_millesime.1}} {% endif %}</div></td>
	</tr>
	{% endfor %}
</table>

{% endblock %} 